### ISSUE TITLE
Just wondering why you have jQuery?

### ISSUE THREAD

**Issue by ayoungh** [shystruk/create-react-redux-app-structure#14]
Hi, Just took a look at this project and it looks cool, but then I saw you're using jQuery, just wondering why and if it is just for the ajax could you not switch over to say Axios? Thanks P.S no offence, just wondered really.

**Comment by shystruk** [comment]
Hi,
Thanks for being interested 👍 
Basically, I use jQuery for window events (resize, scroll), domready and ajax. Moreover, I may have an image slider which is required jQuery. All jQuery is here - https://github.com/shystruk/create-react-redux-app-structure/blob/master/app/helpers/domReady.js
Yes, you can replace ajax with Axios as well. But, if you already use jQuery you should think twice before added one more package ;)

**Comment by ayoungh** [comment]
Thanks, that makes a lot of sense now :) awesome. I hope to have more of a
play with this at the weekend. Awesome work

**Comment by shystruk** [comment]
Happy that you liked 👍 
Join contribute, already have some plans - https://github.com/shystruk/create-react-redux-app-structure/issues ;)
