### ISSUE TITLE
Live or Hot reload

### ISSUE THREAD

**Issue by hootsieroll** [shystruk/create-react-redux-app-structure#18]
Not seeing a way to run live reload or hot module replacement in dev?

**Comment by shystruk** [comment]
Hi,
There is no live reload, you should reload page manually.
npm run dev - watches your files and compiles but does not reload a page

**Comment by hootsieroll** [comment]
Thanks for the quick response!  Wish I had more time to contribute right now, would be a nice feature. :)

**Comment by shystruk** [comment]
You are welcome 👍 
About live reload feature I would suggest making it optional. As for me, I do not use it as want to have a control when reloading a page :)
e.g. npm run dev:reload
