### ISSUE TITLE
getting Yarn error for NPM RUN FAST-START

### ISSUE THREAD

**Issue by prem2282** [shystruk/create-react-redux-app-structure#20]
Hi, I created an app as per the instruction. The app folder is created and I can see all the files.
When I run 'NPM RUN FAST-START' I am getting below error.
I am new this and struck. Please help.

> create-react-redux-app-structure@4.0.0 fast-start C:\Users\meena\Bucky\startRe
dux\myReduxApp
> yarn install && webpack --mode=development && gulp prod && run-p server open-l
ocalhost

'yarn' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! create-react-redux-app-structure@4.0.0 fast-start: `yarn install && web
pack --mode=development && gulp prod && run-p server open-localhost`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the create-react-redux-app-structure@4.0.0 fast-start script.

npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\meena\AppData\Roaming\npm-cache\_logs\2018-06-03T14_10_43_
987Z-debug.log

Here is the Log file

1 verbose cli   'fast-start' ]
2 info using npm@5.6.0
3 info using node@v8.11.2
4 verbose run-script [ 'prefast-start', 'fast-start', 'postfast-start' ]
5 info lifecycle create-react-redux-app-structure@4.0.0~prefast-start: create-react-redux-app-structure@4.0.0
6 info lifecycle create-react-redux-app-structure@4.0.0~fast-start: create-react-redux-app-structure@4.0.0
7 verbose lifecycle create-react-redux-app-structure@4.0.0~fast-start: unsafe-perm in lifecycle true
8 verbose lifecycle create-react-redux-app-structure@4.0.0~fast-start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\meena\Bucky\startRedux\myReduxApp\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;c:\Program Files (x86)\Intel\iCLS Client\;c:\Program Files\Intel\iCLS Client\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\Hewlett-Packard\HP ProtectTools Security Manager\Bin\;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\nodejs\;C:\Users\meena\AppData\Roaming\npm;C:\Users\meena\node_modules
9 verbose lifecycle create-react-redux-app-structure@4.0.0~fast-start: CWD: C:\Users\meena\Bucky\startRedux\myReduxApp
10 silly lifecycle create-react-redux-app-structure@4.0.0~fast-start: Args: [ '/d /s /c',
10 silly lifecycle   'yarn install && webpack --mode=development && gulp prod && run-p server open-localhost' ]
11 silly lifecycle create-react-redux-app-structure@4.0.0~fast-start: Returned: code: 1  signal: null
12 info lifecycle create-react-redux-app-structure@4.0.0~fast-start: Failed to exec fast-start script
13 verbose stack Error: create-react-redux-app-structure@4.0.0 fast-start: `yarn install && webpack --mode=development && gulp prod && run-p server open-localhost`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid create-react-redux-app-structure@4.0.0
15 verbose cwd C:\Users\meena\Bucky\startRedux\myReduxApp
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "fast-start"
18 verbose node v8.11.2
19 verbose npm  v5.6.0
20 error code ELIFECYCLE

**Comment by prem2282** [comment]
I installed yarn thru .msi file but still it did not work.
The path was set wrong in environmental variables. I corrected it. still did not work.

Then I installed yarn thru "npm install yarn -g". it worked.

**Comment by shystruk** [comment]
Hi @prem2282 
Happy that you fixed that. Yes, you should have yarn installed globaly.
