### ISSUE TITLE
Uncaught TypeError: Cannot convert a Symbol value to a string

### ISSUE THREAD

**Issue by MrPeker** [shystruk/create-react-redux-app-structure#28]
I am getting this error on Chrome console after install & run like documentation.
And page is blank.

Uncaught TypeError: Cannot convert a Symbol value to a string
    at Object.o [as f] (web_components_vendor.js:1)
    at ./node_modules/core-js/modules/_hide.js.module.exports (_hide.js:4)
    at Object../node_modules/core-js/modules/es6.symbol.js (es6.symbol.js:228)
    at __webpack_require__ (bootstrap:19)
    at Object../node_modules/core-js/shim.js (shim.js:1)
    at __webpack_require__ (bootstrap:19)
    at Object.<anonymous> (index.js:3)
    at Object../node_modules/babel-polyfill/lib/index.js (index.js:2898)
    at __webpack_require__ (bootstrap:19)
    at Object.0 (module.js:22)

**Comment by shystruk** [comment]
Try to run a build `npm run dev`

**Comment by MrPeker** [comment]
I tried npm run dev and npm run server at another terminal tab but didn't anything changed :/ Everything is same

**Comment by shystruk** [comment]
@MrPeker please use latest version 4.4.0
the issue was in versioning @webcomponents/webcomponentsjs

**Comment by MrPeker** [comment]
Now I'm getting this error.

ERROR in ./app/app.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: Unexpected token (26:4)

  24 |
  25 | ReactDom.render(
> 26 |     <Provider store={store}>
     |     ^
  27 |         <IntlProvider locale={app.locale} messages={messages[locale]}>
  28 |             <Router>
  29 |                 <App/>

 @ multi babel-polyfill ./app/app.jsx index[1]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! create-react-redux-app-structure@4.4.0 fast-start: `yarn install && webpack --mode=development && gulp prod && run-p server open-localhost`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the create-react-redux-app-structure@4.4.0 fast-start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mrpeker/.npm/_logs/2018-09-07T07_25_14_307Z-debug.log
 mrpeker@MrPeker-MacBook-Air  ~/development/GitHub/popupsmart-react 

**Comment by shystruk** [comment]
Try this steps again
```
npm i -g create-react-redux-app-structure
create-react-redux-app-structure my-app
cd my-app/
npm run fast-start
```

**Comment by MrPeker** [comment]
When I create .babelrc file problem solved 
```
{
  "presets": [
    ["es2016"],
    "react",
    "stage-2"
  ],
  "plugins": [
    "babel-plugin-transform-class-properties",
    "transform-object-rest-spread"
  ]
}
```

But the page looks like this. Is this normal?
https://i.hizliresim.com/5yl8gD.png

**Comment by shystruk** [comment]
@MrPeker you do not need to create .babelrc file, it is already there.
What you should do is start from the beginning. Remove already generated project `my-app` example.
Install the latest version `npm i -g create-react-redux-app-structure@latest` and then
```
create-react-redux-app-structure my-app
cd my-app/
npm run fast-start
```
If after installation you see any errors in terminal while doing `create-react-redux-app-structure my-app` then you should restart your terminal :)
